[package]
name = "dumo"
version = "0.1.0"
edition = "2024"
description = "An embedded-graphics backend for Ratatui with an adjustable font size"
documentation = "https://docs.rs/dumo"
readme = true
homepage = "https://crates.io/crates/dumo"
repository = "https://github.com/iddey/dumo"
license = "MIT OR Apache-2.0"
keywords = ["embedded-graphics", "mplusfonts", "ratatui", "tui"]
categories = ["embedded", "graphics", "no-std", "no-std::no-alloc"]
exclude = ["assets", "examples/README.md"]

[dependencies]
embedded-graphics = "0.8.2"
ratatui-core = { version = "0.1.0", features = ["underline-color"] }
defmt = { version = "1.0", optional = true }
mplusfonts = "0.3.3"
thiserror = { version = "2.0", default-features = false }
seq-macro = "0.3.6"
unicode-width = ">=0.2.0, <=0.2.2"

[dev-dependencies]
embedded-graphics-simulator = "0.8.0"
ratatui = { version = "0.30.0", default-features = false }
chrono = { version = "0.4", features = ["clock"] }
tui-big-text = "0.8.2"

[features]
default = [
    "alloc",
    "font-latin",
    "font-tui-block",
    "font-tui-boxes",
    "font-tui-dots-2x4",
    "font-tui-rect-2x3",
    "font-tui-rect-2x4",
]

# Enables the backend wrapper that buffers and redraws text that should blink.
alloc = ["defmt?/alloc"]

# Allows the types in this crate and its dependencies to be formatted via defmt.
defmt = ["dep:defmt", "embedded-graphics/defmt", "mplusfonts/defmt"]

# Enables bitmap fonts with a cell size of 6 by 16 pixels. Complements bit depth features.
font-6x16 = []

# Enables bitmap fonts with a cell size of 6 by 18 pixels. Complements bit depth features.
font-6x18 = []

# Enables bitmap fonts with a cell size of 8 by 20 pixels. Complements bit depth features.
font-8x20 = []

# Enables bitmap fonts with a cell size of 8 by 24 pixels. Complements bit depth features.
font-8x24 = []

# Enables bitmap fonts with a cell size of 8 by 24 pixels, bold. Complements bit depth features.
font-8x24-bold = []

# Enables bitmap fonts with a cell size of 10 by 30 pixels. Complements bit depth features.
font-10x30 = []

# Enables bitmap fonts with a cell size of 12 by 30 pixels. Complements bit depth features.
font-12x30 = []

# Enables bitmap fonts with a cell size of 12 by 36 pixels. Complements bit depth features.
font-12x36 = []

# Enables bitmap fonts with a cell size of 12 by 36 pixels, bold. Complements bit depth features.
font-12x36-bold = []

# Enables bitmap fonts with a cell size of 14 by 42 pixels. Complements bit depth features.
font-14x42 = []

# Enables bitmap fonts with a cell size of 16 by 40 pixels. Complements bit depth features.
font-16x40 = []

# Enables bitmap fonts with a cell size of 16 by 48 pixels. Complements bit depth features.
font-16x48 = []

# Enables bitmap fonts with a bit depth of 1 bit per pixel. Complements font size features.
font-1-bit = []

# Enables bitmap fonts with a bit depth of 2 bits per pixel. Complements font size features.
font-2-bits = []

# Enables bitmap fonts with a bit depth of 4 bits per pixel. Complements font size features.
font-4-bits = []

# Enables bitmap fonts with a bit depth of 8 bits per pixel. Complements font size features.
font-8-bits = []

# Adds 537 Unicode code points, including ASCII characters, to each constant enabled.
font-latin = []

# Adds 74 Unicode code points, the generic block characters, to each constant enabled.
font-tui-block = []

# Adds 130 Unicode code points, the box-drawing characters, to each constant enabled.
font-tui-boxes = []

# Adds 257 Unicode code points, the braille patterns, to each constant enabled.
font-tui-dots-2x4 = []

# Adds 64 Unicode code points, the block sextants, to each constant enabled.
font-tui-rect-2x3 = []

# Adds 256 Unicode code points, the block octants, to each constant enabled.
font-tui-rect-2x4 = []

# Adds 113 Unicode code points, the hiragana letters, to each constant enabled.
font-hiragana = []

# Adds 120 Unicode code points, the katakana letters, to each constant enabled.
font-katakana = []

[package.metadata.docs.rs]
features = [
    "font-6x16",
    "font-6x18",
    "font-8x20",
    "font-8x24",
    "font-8x24-bold",
    "font-10x30",
    "font-12x30",
    "font-12x36",
    "font-12x36-bold",
    "font-14x42",
    "font-16x40",
    "font-16x48",
    "font-1-bit",
    "font-2-bits",
    "font-4-bits",
    "font-8-bits",
]

[[example]]
name = "cursor-1"
required-features = ["alloc"]

[[example]]
name = "cursor-2"
required-features = [
    "alloc",
    "font-8x24",
    "font-8x24-bold",
    "font-4-bits",
    "font-latin",
    "font-tui-block",
    "font-tui-boxes",
    "font-tui-dots-2x4",
    "font-tui-rect-2x3",
    "font-tui-rect-2x4",
]

[[example]]
name = "styles-1"
required-features = ["alloc"]
