[workspace]
resolver = "3"
members = ["esp32s3", "rp2350a"]

[workspace.package]
readme = true
repository = "https://github.com/iddey/dumo"
license = "MIT OR Apache-2.0"
publish = false

[workspace.dependencies]
cortex-m-rt = "0.7.5"
dumo.path = "../.."
embassy-embedded-hal = "0.5.0"
embassy-executor = { version = "0.9.1", features = ["executor-thread"] }
embassy-futures = "0.1.2"
embassy-sync = "0.7.2"
embassy-rp = { version = "0.9.0", features = ["time-driver"] }
embassy-time = "0.5.0"
embedded-alloc = "0.7.0"
embedded-graphics = "0.8.2"
esp-alloc = "0.9.0"
esp-bootloader-esp-idf = "0.4.0"
esp-hal = { version = "1.0.0", features = ["unstable"] }
esp-rtos = { version = "0.2.0", features = ["embassy"] }
heapless = "0.9.2"
mipidsi = "0.10.0"
panic-halt = "1.0.0"
portable-atomic = "1.13.1"
static_cell = "2.1.1"

[workspace.dependencies.ratatui]
version = "0.30.0"
default-features = false

[workspace.dependencies.strum]
version = "0.28.0"
default-features = false
features = ["derive"]
